/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutEventEventIdImport } from './routes/_layout/event/$eventId'
import { Route as LayoutEventEventIdBuyImport } from './routes/_layout/event_/$eventId/buy'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutEventEventIdRoute = LayoutEventEventIdImport.update({
  id: '/event/$eventId',
  path: '/event/$eventId',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutEventEventIdBuyRoute = LayoutEventEventIdBuyImport.update({
  id: '/event_/$eventId/buy',
  path: '/event/$eventId/buy',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/event/$eventId': {
      id: '/_layout/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/event/$eventId'
      preLoaderRoute: typeof LayoutEventEventIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/event_/$eventId/buy': {
      id: '/_layout/event_/$eventId/buy'
      path: '/event/$eventId/buy'
      fullPath: '/event/$eventId/buy'
      preLoaderRoute: typeof LayoutEventEventIdBuyImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutEventEventIdRoute: typeof LayoutEventEventIdRoute
  LayoutEventEventIdBuyRoute: typeof LayoutEventEventIdBuyRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutEventEventIdRoute: LayoutEventEventIdRoute,
  LayoutEventEventIdBuyRoute: LayoutEventEventIdBuyRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/event/$eventId': typeof LayoutEventEventIdRoute
  '/event/$eventId/buy': typeof LayoutEventEventIdBuyRoute
}

export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/event/$eventId': typeof LayoutEventEventIdRoute
  '/event/$eventId/buy': typeof LayoutEventEventIdBuyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/event/$eventId': typeof LayoutEventEventIdRoute
  '/_layout/event_/$eventId/buy': typeof LayoutEventEventIdBuyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/' | '/event/$eventId' | '/event/$eventId/buy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/event/$eventId' | '/event/$eventId/buy'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/_layout/event/$eventId'
    | '/_layout/event_/$eventId/buy'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/",
        "/_layout/event/$eventId",
        "/_layout/event_/$eventId/buy"
      ]
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/event/$eventId": {
      "filePath": "_layout/event/$eventId.tsx",
      "parent": "/_layout"
    },
    "/_layout/event_/$eventId/buy": {
      "filePath": "_layout/event_/$eventId/buy.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
